name: VisasQ Watcher

on:
  schedule:
    # 09:07 JST = 00:07 UTC
    - cron: "7 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write  # state/seen_ids.json をコミットするため

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python visasq_scraper.py

      - name: Commit state (seen_ids.json)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state/seen_ids.json
          git diff --cached --quiet && echo "No state changes." || (git commit -m "chore: update state [skip ci]" && git push)


